
theme:  just-the-docs
remote_theme: just-the-docs/just-the-docs
# Common settings for all themes
title: React Tutorial - Quotes App
description: A step-by-step guide to building a React application
footer: false